### ISSUE TITLE
Authorization required even for public packages

### ISSUE THREAD

**Issue by djspiewak** [djspiewak/sbt-github-packages#4]
It appears that authorization is required to download even public packages. The plugin should probably reflect this by requiring `githubTokenSource` and such.

**Comment by Poorva17** [comment]
Hello @djspiewak , we are using this plugin to publishing/resolving artifacts of github. We could publish artifact on github. 👍 

But we are having following questions:
1.  Artifact id generated doesn't seem right to me. 
```
<dependency>
  <groupId>com.codecommit.sbt-github-packages-tests-publish_2</groupId>
  <artifactId>12</artifactId>
  <version>0.2.1</version>
</dependency>
```
I was expecting following
```
<dependency>
  <groupId>com.codecommit</groupId>
  <artifactId>sbt-github-packages-tests-publish_2.12</artifactId>
  <version>0.2.1</version>
 </dependency>
```

2. As mentioned in current issue, it seems even for downloading packages it required authentication which seems unusual as other package repositories require only resolver to be added for downloading. (e.g. - bintray and jitpack). **I could not resolve my published packages even after adding `githubTokenSource` with `read:packages` permission.**  It gives me unauthorized error. My guess is it might not be resolving because of different format of maven dependency explained in point 1.

**Comment by djspiewak** [comment]
So the artifact ids that are displayed in the web UI are incorrect, but this is a display issue only! If you use the correct artifact id (i.e. the one you expected, *not* the one shown by github), it should work as a dependency.

Regarding the authentication issues… it does appear that there are some problems there. Resolving from public repositories should theoretically be doable anonymously, but it's not clear that github is doing this correctly. I think if you use the corrected artifact id, though, it should work.

**Comment by Poorva17** [comment]
@djspiewak Is there any progress on topic of `github needs authorization for downloading public packages`. Any workaround for this?

**Comment by djspiewak** [comment]
@Poorva17 As far as I can tell, this is simply how GitHub designed Packages to behave. :-( I'm not entirely sure *why* they're doing it this way, but I would guess it has something to do with how their DoS protection currently works. This, as well as the lack of aggregate repositories, is what I would consider to be the primary pair of weaknesses in the service as it stands.
